modules:
  bow:
    enabled: true
  motd:
    enabled: true
  recipe:
    enabled: true
  torch:
    enabled: true
  chat:
    enabled: true
  tab:
    enabled: true
  spawner:
    enabled: true
  adventure:
    enabled: true